# https://taskfile.dev
version: '3'
vars:
  BINFILE: retry

includes:
  dev: ./Taskfile_dev.yml

tasks:
  default:
    desc: "List tasks"
    cmds:
      - task -a

  binary:
    desc: "Build binary"
    cmds:
      # - go generate ./...
      - CGO_ENABLED=0 go build -o {{.BINFILE}} cmd/*.go
    # silent: true

  linter:
    desc: "Run linter"
    cmds:
      - golangci-lint run

  cover:
    desc: "Run unit tests"
    cmds:
      - go generate ./...
      - go test -coverpkg=./... -coverprofile=profile.cov ./...
      - go tool cover -func profile.cov
      - rm profile.cov

  tests:
    desc: "Run tests"
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log"

  snapshot:
    desc: "Create snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean
